version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    executor:
      name: node/default
    steps:
      - run: npm install
      - run: npm run test
      - run:
          name: Deploy
          command: curl -X POST -d {} ${hook}
